### ISSUE TITLE
how to run the script manually?

### ISSUE THREAD

**Issue by indicozy** [gamcoh/translations-checker#1]
I can't use it as pre-commit hook since it requires discussion with dev team, but I want to test it in NextJS application. How can I run it manually?

**Comment by gamcoh** [comment]
Hi,

Here's the steps to use this project as a standalone script:
1. git clone the project.
2. Build the compiled program using: `cargo build --release --bins`
3. Simply run it like so:
```sh
./target/release/translation_checker file1.ts file2.js file3.tsx --json-file en.json
```
Where file1.ts and the others are files from your repo that you want to check against your json file which is where the translations are.
