### ISSUE TITLE
Checker is not considering hooks's arguments

### ISSUE THREAD

**Issue by indicozy** [gamcoh/translations-checker#2]
I have code like this:
```
  const t = useTranslations('pdp');
return (
          <TabTitle id={showFrameDetails ? 1 : 0} value='lenses'>
            {isContactLens ? t('how_to_wear_them') : t('lenses')}
          </TabTitle>
)
```

Checker does not consider `'pdp'` part and checks it as `'how_to_wear_them`. We have value for `'pdp.how_to_wear_them'`

**Comment by gamcoh** [comment]
I'll see what I can do

**Comment by gamcoh** [comment]
You can check the release of the new version to see how I'm now considering the hooks : https://github.com/gamcoh/translations-checker/releases/tag/v0.1.9
